export const hospitalSeedData = [
  {
    name: 'Government General Hospital Hyderabad',
    address: 'Afzal Gunj Road, near Osmania Medical College',
    village: 'Afzal Gunj',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    contactNumber: '+91 40 2460 0123',
    emergencyAvailable: true,
    openingHours: '24 hours',
    latitude: 17.3713,
    longitude: 78.4747,
    departments: ['Emergency', 'Cardiology', 'Orthopedics', 'Pediatrics', 'General Medicine'],
    doctorsCount: 126,
    bedsAvailable: 184,
    ambulanceAvailable: true,
    rating: 4.4,
    reviews: [{ author: 'Asha R.', text: 'Fast emergency support and clear guidance from staff.', rating: 5 }],
    imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=900&q=80'
  },
  {
    name: 'Lok Nayak Government Hospital',
    address: 'Jawaharlal Nehru Marg, Delhi Gate',
    village: 'Delhi Gate',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    contactNumber: '+91 11 2323 2400',
    emergencyAvailable: true,
    openingHours: '24 hours',
    latitude: 28.6388,
    longitude: 77.2386,
    departments: ['Trauma Care', 'Neurology', 'ENT', 'Surgery', 'Diagnostics'],
    doctorsCount: 210,
    bedsAvailable: 312,
    ambulanceAvailable: true,
    rating: 4.5,
    reviews: [{ author: 'Neha S.', text: 'Excellent trauma care team.', rating: 5 }],
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=900&q=80'
  },
  {
    name: 'King Edward Memorial Government Hospital',
    address: 'Acharya Donde Marg, Parel',
    village: 'Parel',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    contactNumber: '+91 22 2410 7000',
    emergencyAvailable: true,
    openingHours: '24 hours',
    latitude: 19.0026,
    longitude: 72.8426,
    departments: ['Emergency', 'Oncology', 'Maternity', 'Dermatology', 'Radiology'],
    doctorsCount: 248,
    bedsAvailable: 275,
    ambulanceAvailable: true,
    rating: 4.6,
    reviews: [{ author: 'Prakash M.', text: 'Strong specialist departments and affordable care.', rating: 5 }],
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=900&q=80'
  }
];
